package formation_sopra.biblio.model;

import static org.assertj.core.api.Assertions.assertThat;

public class AuteurAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuteurAllPropertiesEquals(Auteur expected, Auteur actual) {
        assertAuteurAutoGeneratedPropertiesEquals(expected, actual);
        assertAuteurAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuteurAllUpdatablePropertiesEquals(Auteur expected, Auteur actual) {
        assertAuteurUpdatableFieldsEquals(expected, actual);
        assertAuteurUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuteurAutoGeneratedPropertiesEquals(Auteur expected, Auteur actual) {
        assertThat(actual)
            .as("Verify Auteur auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuteurUpdatableFieldsEquals(Auteur expected, Auteur actual) {
        assertThat(actual)
            .as("Verify Auteur relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getPrenom()).as("check prenom").isEqualTo(expected.getPrenom()))
            .satisfies(a -> assertThat(a.getNationalite()).as("check nationalite").isEqualTo(expected.getNationalite()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuteurUpdatableRelationshipsEquals(Auteur expected, Auteur actual) {
        // empty method
    }
}
