package formation_sopra.biblio.model;

import static org.assertj.core.api.Assertions.assertThat;

public class AvisAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvisAllPropertiesEquals(Avis expected, Avis actual) {
        assertAvisAutoGeneratedPropertiesEquals(expected, actual);
        assertAvisAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvisAllUpdatablePropertiesEquals(Avis expected, Avis actual) {
        assertAvisUpdatableFieldsEquals(expected, actual);
        assertAvisUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvisAutoGeneratedPropertiesEquals(Avis expected, Avis actual) {
        assertThat(actual)
            .as("Verify Avis auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvisUpdatableFieldsEquals(Avis expected, Avis actual) {
        assertThat(actual)
            .as("Verify Avis relevant properties")
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()))
            .satisfies(a -> assertThat(a.getCommentaire()).as("check commentaires").isEqualTo(expected.getCommentaire()))
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvisUpdatableRelationshipsEquals(Avis expected, Avis actual) {
        assertThat(actual)
            .as("Verify Avis relationships")
            .satisfies(a -> assertThat(a.getLivre()).as("check livre").isEqualTo(expected.getLivre()));
    }
}
