package formation_sopra.biblio.model;

import static org.assertj.core.api.Assertions.assertThat;

public class EditeurAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEditeurAllPropertiesEquals(Editeur expected, Editeur actual) {
        assertEditeurAutoGeneratedPropertiesEquals(expected, actual);
        assertEditeurAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEditeurAllUpdatablePropertiesEquals(Editeur expected, Editeur actual) {
        assertEditeurUpdatableFieldsEquals(expected, actual);
        assertEditeurUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEditeurAutoGeneratedPropertiesEquals(Editeur expected, Editeur actual) {
        assertThat(actual)
            .as("Verify Editeur auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEditeurUpdatableFieldsEquals(Editeur expected, Editeur actual) {
        assertThat(actual)
            .as("Verify Editeur relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getPays()).as("check pays").isEqualTo(expected.getPays()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEditeurUpdatableRelationshipsEquals(Editeur expected, Editeur actual) {
        // empty method
    }
}
