// package formation_sopra.biblio.model;

// import static org.assertj.core.api.Assertions.assertThat;

// public class GenreAsserts {

//     /**
//      * Asserts that the entity has all properties (fields/relationships) set.
//      *
//      * @param expected the expected entity
//      * @param actual the actual entity
//      */
//     public static void assertGenreAllPropertiesEquals(Genre expected, Genre actual) {
//         assertGenreAutoGeneratedPropertiesEquals(expected, actual);
//         assertGenreAllUpdatablePropertiesEquals(expected, actual);
//     }

//     /**
//      * Asserts that the entity has all updatable properties (fields/relationships) set.
//      *
//      * @param expected the expected entity
//      * @param actual the actual entity
//      */
//     public static void assertGenreAllUpdatablePropertiesEquals(Genre expected, Genre actual) {
//         assertGenreUpdatableFieldsEquals(expected, actual);
//         assertGenreUpdatableRelationshipsEquals(expected, actual);
//     }

//     /**
//      * Asserts that the entity has all the auto generated properties (fields/relationships) set.
//      *
//      * @param expected the expected entity
//      * @param actual the actual entity
//      */
//     public static void assertGenreAutoGeneratedPropertiesEquals(Genre expected, Genre actual) {
//         assertThat(actual)
//             .as("Verify Genre auto generated properties")
//             .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
//     }

//     /**
//      * Asserts that the entity has all the updatable fields set.
//      *
//      * @param expected the expected entity
//      * @param actual the actual entity
//      */
//     public static void assertGenreUpdatableFieldsEquals(Genre expected, Genre actual) {
//         assertThat(actual)
//             .as("Verify Genre relevant properties")
//             .satisfies(a -> assertThat(a.getLibelle()).as("check libelle").isEqualTo(expected.getLibelle()));
//     }

//     /**
//      * Asserts that the entity has all the updatable relationships set.
//      *
//      * @param expected the expected entity
//      * @param actual the actual entity
//      */
//     public static void assertGenreUpdatableRelationshipsEquals(Genre expected, Genre actual) {
//         assertThat(actual)
//             .as("Verify Genre relationships")
//             .satisfies(a -> assertThat(a.getLivres()).as("check livres").isEqualTo(expected.getLivres()));
//     }
// }
