package formation_sopra.biblio.model;

import static org.assertj.core.api.Assertions.assertThat;

public class LivreAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLivreAllPropertiesEquals(Livre expected, Livre actual) {
        assertLivreAutoGeneratedPropertiesEquals(expected, actual);
        assertLivreAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLivreAllUpdatablePropertiesEquals(Livre expected, Livre actual) {
        assertLivreUpdatableFieldsEquals(expected, actual);
        assertLivreUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLivreAutoGeneratedPropertiesEquals(Livre expected, Livre actual) {
        assertThat(actual)
            .as("Verify Livre auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLivreUpdatableFieldsEquals(Livre expected, Livre actual) {
        assertThat(actual)
            .as("Verify Livre relevant properties")
            .satisfies(a -> assertThat(a.getTitre()).as("check titre").isEqualTo(expected.getTitre()))
            .satisfies(a -> assertThat(a.getResume()).as("check resume").isEqualTo(expected.getResume()))
            .satisfies(a -> assertThat(a.getAnnee()).as("check annee").isEqualTo(expected.getAnnee()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLivreUpdatableRelationshipsEquals(Livre expected, Livre actual) {
        assertThat(actual)
            .as("Verify Livre relationships")
            .satisfies(a -> assertThat(a.getAuteur()).as("check auteur").isEqualTo(expected.getAuteur()))
            .satisfies(a -> assertThat(a.getEditeur()).as("check editeur").isEqualTo(expected.getEditeur()))
            .satisfies(a -> assertThat(a.getCollection()).as("check collection").isEqualTo(expected.getCollection()));
    }
}
