pipeline {
    agent any

    stages {

        stage('NPM build') {
            // Demander à Jenkins d'exécuter le builder dans un container Docker
            agent {
                docker {
                    image 'node:lts-bullseye'
                    args '''
                        -v $HOME/.npm:/root/.npm:z
                        -u root
                        --network devops
                    '''
                    reuseNode true // Permet de garder le même workspace entre les différents agents (any & docker)
                }
            }

            steps {
                dir('biblio-angular') {
                    sh 'npm install'
                    sh 'npm install -D @sonar/scan'

                    withSonarQubeEnv('sonar-scanner') {
                        sh './node_modules/.bin/sonar-scanner -Dsonar.projectKey=biblio-angular'
                    }

                    sh './node_modules/.bin/ng build'
                }
            }
        }

        stage('Docker build') {
            steps {
                dir('biblio-angular') {
                    sh 'docker build -t ajc/biblio-angular .'
                }
            }
        }

        stage('Docker deploy') {
            steps {
                  // Se placer dans le répertoire (éventuellement) dans lequel se trouve le docker-compose.yml
                  sh 'docker compose up -d --no-deps angular'
                }

        }
    }
}
